[package]
name = "gyro_motors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.16.1", features = ["hal"] }
mpu6050="0.1.6"
embedded-hal = "0.2.7"
anyhow="1.0"