[package]
name = "bidule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.0"
rppal = {version="0.17.1",features=["hal"]}
tokio = {version="1", features=["full"]}
